services:
  - type: web
    name: chan-tv
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn chantv.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "chantv.onrender.com,.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://chantv.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: chan-tv-db
          property: connectionString
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: chan-tv-db
    databaseName: chantv
    user: chantv