# Generated by Django 5.2.17 on 2026-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_league_subscriptionplan_team_profile_rental_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4 or browser-compatible video file', upload_to='videos/%Y/%m/'),
        ),
    ]
